---
- name: Add clickhouse addresses to /etc/hosts
  become: true
  lineinfile:
    dest: /etc/hosts
    regexp: '.*{{ item }}$'
    line: "{{ hostvars[item].ansible_host }} {{item}}"
    state: present
  when: hostvars[item].ansible_host is defined
  with_items: "{{ groups.clickhouse }}"
#Устанавливаем доступ к репозиторию
- name: Install epel-release package
  become: true
  ansible.builtin.yum:
    name: epel-release
    state: present
#Обновление списка пакетов
- name: Update repositories
  become: true
  ansible.builtin.yum:
    name: '*'
    state: latest
#Установка пакетов NGINX и unzip
- name: Install Nginx and Unzip
  become: true
  ansible.builtin.yum:
    name:
      - nginx
      - unzip
    state: present
#Получаем пакет из репозитория. Адрес репозитория (переменная - lighthouse_distrib) прописывается в переменных (group_vars/lighthouse/vars.yml)
- name: Get lighthouse distrib
  ansible.builtin.get_url:
    url: "{{ lighthouse_distrib }}"
    dest: ./lighthouse.zip
#Создание директории для Lighthouse. Директория, где будет расположена Lighthouse (переменная - lighthouse_location_dir)
#прописывается в переменных (group_vars/lighthouse/vars.yml)
- name: Create directory
  become: true
  file:
    path: "{{ lighthouse_location_dir }}"
    state: directory
    force: yes
#Распаковка пакета Lighthouse. Директория, где будет расположена Lighthouse (переменная - lighthouse_location_dir)
#прописывается в переменных (group_vars/lighthouse/vars.yml)
- name: Unpack lighthouse archive
  become: true
  ansible.builtin.unarchive:
    src: /home/centos/lighthouse.zip
    dest: "{{ lighthouse_location_dir }}"
    remote_src: yes
# Создания файла конфигурации lighthouse
- name: NGINX | Create file for lighthouse config
  become: true
  ansible.builtin.file:
    path: /etc/nginx/conf.d/lighthouse.conf
    state: touch
    mode: 0644
  tags: nginx
# Создания файла конфигурации lighthouse
- name: Lighthouse | Create lighthouse config
  become: true
  template:
    src: lighthouse.conf.j2
    dest: /etc/nginx/conf.d/lighthouse.conf
    mode: 0644
  tags: lighthouse
# Создания файла конфигурации nginx
- name: NGINX | Create general config
  become: true
  template:
    src: templates/nginx.conf.j2
    dest: /etc/nginx/nginx.conf
    mode: 0644
  #Рестарт NGINX после правки конфигураций
  notify: Start nginx service
  tags: nginx
